title: CVBuilder.dev
tagline: Write your CV in HTML/CSS
description: Write your CV / Resume Easily with HTML & CSS!
url: https://cvbuilder.dev

theme: null

license:
  name: MIT
  url: https://github.com/BenSouchet/cvbuilder.dev/blob/main/LICENSE

maintainers:
  - name: Ben Souchet
    url: https://github.com/BenSouchet

encoding: "utf-8"

kramdown:
  input: Kramdown

exclude: ["node_modules/", "package.json", "package-lock.json", "*.gemspec", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "assets/js/modules/", "assets/css/style.scss"]

sass:
  style: compressed
